service:
  name: vf-deploy-service
# app and org for use with dashboard.serverless.com
app: vf-deploy-app
org: jlehr

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: ${opt:region, 'us-west-2'}
  stage: ${opt:stage, 'dev'}
  stackName: ${opt:stackName, 'dev-stack'}
  deploymentBucket:
    name: bitiverse-sls-deployments
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - "s3:GetObject"
        - "s3:ListBucket"
      Resource:
         Fn::Join:
           - ""
           - - "arn:aws:s3:::"
             - ${self:provider.deploymentBucket}
             

functions:
  initstack:
    handler: handler.initstack
    environment:
      APP_NAME: ${self:app}
      SLS_STAGE_NAME: ${self:provider.stage}
      STACK_NAME: ${self:provider.stackName}
      SLS_DEPLOY_BUCKET: ${self:provider.deploymentBucket}
